unearth:
  block:
    fish_destroyed:
      base: "ia:elitefantasy:fish_destroyed_sand_1" #Item base
      tool:
        - ia:elitefantasy:big_brush
        - ia:elitefantasy:brush_bone
      transformation:
        stages:
          1:
            block_id: "ia:elitefantasy:fish_destroyed_sand_2"
            #remove_item_main_hand: true
            #reduce_durability: 100
            #reduce_usages_ia: 1
          2:
            block_id: "ia:elitefantasy:fish_destroyed_sand_3"
          3:
            block_id: "ia:elitefantasy:fish_destroyed_sand_4"
          4:
            block_id: "ia:elitefantasy:fish_destroyed_sand_5"
            drops:
              - "ia:elitefantasy:fish_destroyed_1;1-64;55"
  furniture:
    fish_destroyed:
      base: "ia:elitefantasy:fish_destroyed_sand_1" #Item base
      tool:
        - ia:elitefantasy:big_brush
        - ia:elitefantasy:brush_bone
      transformation:
        stages:
          1:
            furniture_id: "ia:elitefantasy:fish_destroyed_sand_2"
          2:
            furniture_id: "ia:elitefantasy:fish_destroyed_sand_3"
          3:
            furniture_id: "ia:elitefantasy:fish_destroyed_sand_4"
          4:
            furniture_id: "ia:elitefantasy:fish_destroyed_sand_5"
            remove: true
            only_one_drop: false
            drops:
              - "ia:elitefantasy:fish_destroyed_1;1-64;55"