name: UnearthMechanic
version: '${version}'
main: dev.wuason.unearthMechanic.UnearthMechanic
api-version: '1.18'
authors: [ Wuason ]
website: wiki.techmc.es
depend:
  - Mechanics
softdepend:
  - ItemsAdder
  - Oraxen
  - WorldGuard
  - Nexo
  - CraftEngine
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:2.0.20"
permissions:
  unearthMechanic.bypass:
    description: Allows the player to bypass the UnearthMechanic
    default: op